<?php

namespace ContainerQBNN73J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sgib6oKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Sgib6oK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sgib6oK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'biblioIRIS' => ['privates', '.errored..service_locator.Sgib6oK.App\\Entity\\BiblioIRIS', NULL, 'Cannot autowire service ".service_locator.Sgib6oK": it references class "App\\Entity\\BiblioIRIS" but no such service exists.'],
            'biblioIRISRepository' => ['privates', 'App\\Repository\\BiblioIRISRepository', 'getBiblioIRISRepositoryService', true],
        ], [
            'biblioIRIS' => 'App\\Entity\\BiblioIRIS',
            'biblioIRISRepository' => 'App\\Repository\\BiblioIRISRepository',
        ]);
    }
}
