<?php

namespace ContainerQBNN73J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WySrxSpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wySrxSp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wySrxSp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'blameRepository' => ['privates', 'App\\Repository\\BlameRepository', 'getBlameRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'blameRepository' => 'App\\Repository\\BlameRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
