<?php

namespace ContainerQBNN73J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UG6N04OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UG6N04O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UG6N04O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\nest\\BlameController::delete' => ['privates', '.service_locator.OuXk1hg', 'get_ServiceLocator_OuXk1hgService', true],
            'App\\Controller\\nest\\BlameController::edit' => ['privates', '.service_locator.vwP5J1y', 'get_ServiceLocator_VwP5J1yService', true],
            'App\\Controller\\nest\\BlameController::index' => ['privates', '.service_locator.OuXk1hg', 'get_ServiceLocator_OuXk1hgService', true],
            'App\\Controller\\nest\\BlameController::new' => ['privates', '.service_locator.wySrxSp', 'get_ServiceLocator_WySrxSpService', true],
            'App\\Controller\\nest\\BlameController::update' => ['privates', '.service_locator.NsrUy3Y', 'get_ServiceLocator_NsrUy3YService', true],
            'App\\Controller\\nest\\LibraryController::delete' => ['privates', '.service_locator.pwMpaaB', 'get_ServiceLocator_PwMpaaBService', true],
            'App\\Controller\\nest\\LibraryController::edit' => ['privates', '.service_locator.rZXgnRB', 'get_ServiceLocator_RZXgnRBService', true],
            'App\\Controller\\nest\\LibraryController::index' => ['privates', '.service_locator.pwMpaaB', 'get_ServiceLocator_PwMpaaBService', true],
            'App\\Controller\\nest\\LibraryController::new' => ['privates', '.service_locator.pwMpaaB', 'get_ServiceLocator_PwMpaaBService', true],
            'App\\Controller\\nest\\LibraryController::update' => ['privates', '.service_locator.Sgib6oK', 'get_ServiceLocator_Sgib6oKService', true],
            'App\\Controller\\nest\\MainController::index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\nest\\UserController::blameList' => ['privates', '.service_locator.OuXk1hg', 'get_ServiceLocator_OuXk1hgService', true],
            'App\\Controller\\nest\\UserController::index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\nest\\BlameController:delete' => ['privates', '.service_locator.OuXk1hg', 'get_ServiceLocator_OuXk1hgService', true],
            'App\\Controller\\nest\\BlameController:edit' => ['privates', '.service_locator.vwP5J1y', 'get_ServiceLocator_VwP5J1yService', true],
            'App\\Controller\\nest\\BlameController:index' => ['privates', '.service_locator.OuXk1hg', 'get_ServiceLocator_OuXk1hgService', true],
            'App\\Controller\\nest\\BlameController:new' => ['privates', '.service_locator.wySrxSp', 'get_ServiceLocator_WySrxSpService', true],
            'App\\Controller\\nest\\BlameController:update' => ['privates', '.service_locator.NsrUy3Y', 'get_ServiceLocator_NsrUy3YService', true],
            'App\\Controller\\nest\\LibraryController:delete' => ['privates', '.service_locator.pwMpaaB', 'get_ServiceLocator_PwMpaaBService', true],
            'App\\Controller\\nest\\LibraryController:edit' => ['privates', '.service_locator.rZXgnRB', 'get_ServiceLocator_RZXgnRBService', true],
            'App\\Controller\\nest\\LibraryController:index' => ['privates', '.service_locator.pwMpaaB', 'get_ServiceLocator_PwMpaaBService', true],
            'App\\Controller\\nest\\LibraryController:new' => ['privates', '.service_locator.pwMpaaB', 'get_ServiceLocator_PwMpaaBService', true],
            'App\\Controller\\nest\\LibraryController:update' => ['privates', '.service_locator.Sgib6oK', 'get_ServiceLocator_Sgib6oKService', true],
            'App\\Controller\\nest\\MainController:index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\nest\\UserController:blameList' => ['privates', '.service_locator.OuXk1hg', 'get_ServiceLocator_OuXk1hgService', true],
            'App\\Controller\\nest\\UserController:index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\nest\\BlameController::delete' => '?',
            'App\\Controller\\nest\\BlameController::edit' => '?',
            'App\\Controller\\nest\\BlameController::index' => '?',
            'App\\Controller\\nest\\BlameController::new' => '?',
            'App\\Controller\\nest\\BlameController::update' => '?',
            'App\\Controller\\nest\\LibraryController::delete' => '?',
            'App\\Controller\\nest\\LibraryController::edit' => '?',
            'App\\Controller\\nest\\LibraryController::index' => '?',
            'App\\Controller\\nest\\LibraryController::new' => '?',
            'App\\Controller\\nest\\LibraryController::update' => '?',
            'App\\Controller\\nest\\MainController::index' => '?',
            'App\\Controller\\nest\\UserController::blameList' => '?',
            'App\\Controller\\nest\\UserController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\nest\\BlameController:delete' => '?',
            'App\\Controller\\nest\\BlameController:edit' => '?',
            'App\\Controller\\nest\\BlameController:index' => '?',
            'App\\Controller\\nest\\BlameController:new' => '?',
            'App\\Controller\\nest\\BlameController:update' => '?',
            'App\\Controller\\nest\\LibraryController:delete' => '?',
            'App\\Controller\\nest\\LibraryController:edit' => '?',
            'App\\Controller\\nest\\LibraryController:index' => '?',
            'App\\Controller\\nest\\LibraryController:new' => '?',
            'App\\Controller\\nest\\LibraryController:update' => '?',
            'App\\Controller\\nest\\MainController:index' => '?',
            'App\\Controller\\nest\\UserController:blameList' => '?',
            'App\\Controller\\nest\\UserController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
