<?php

namespace ContainerQBNN73J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlame2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vwP5J1y.App\Entity\Blame' shared service.
     *
     * @return \App\Entity\Blame
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.vwP5J1y": it references class "App\\Entity\\Blame" but no such service exists.');
    }
}
