<?php

namespace ContainerQBNN73J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBiblioIRISService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Sgib6oK.App\Entity\BiblioIRIS' shared service.
     *
     * @return \App\Entity\BiblioIRIS
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Sgib6oK": it references class "App\\Entity\\BiblioIRIS" but no such service exists.');
    }
}
