<?php

namespace Container6ZE8nKM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PwMpaaBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pwMpaaB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pwMpaaB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'biblioIRISRepository' => ['privates', 'App\\Repository\\BiblioIRISRepository', 'getBiblioIRISRepositoryService', true],
        ], [
            'biblioIRISRepository' => 'App\\Repository\\BiblioIRISRepository',
        ]);
    }
}
