<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAo93sep\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAo93sep/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAo93sep.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAo93sep\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAo93sep\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ao93sep',
    'container.build_id' => '8ecd9c4f',
    'container.build_time' => 1671222910,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAo93sep');
