<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQBNN73J\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQBNN73J/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQBNN73J.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQBNN73J\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQBNN73J\App_KernelDevDebugContainer([
    'container.build_hash' => 'QBNN73J',
    'container.build_id' => 'ef0ad264',
    'container.build_time' => 1674679584,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQBNN73J');
