<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.9baafadc.js',
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_bootstrap_dist_js_boo-94a78f.c05e959d.js',
                '/build/app.b1fc88ef.js',
            ],
            'css' => [
                '/build/app.c6e8c275.css',
            ],
        ],
    ],
],

]];
