<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'id', '' . "\0" . 'App\\Entity\\User' . "\0" . 'email', '' . "\0" . 'App\\Entity\\User' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\User' . "\0" . 'password', '' . "\0" . 'App\\Entity\\User' . "\0" . 'fName', '' . "\0" . 'App\\Entity\\User' . "\0" . 'lName', '' . "\0" . 'App\\Entity\\User' . "\0" . 'phone', '' . "\0" . 'App\\Entity\\User' . "\0" . 'birthday', '' . "\0" . 'App\\Entity\\User' . "\0" . 'adress', '' . "\0" . 'App\\Entity\\User' . "\0" . 'img', '' . "\0" . 'App\\Entity\\User' . "\0" . 'university', '' . "\0" . 'App\\Entity\\User' . "\0" . 'studyField', '' . "\0" . 'App\\Entity\\User' . "\0" . 'requests', '' . "\0" . 'App\\Entity\\User' . "\0" . 'orders', '' . "\0" . 'App\\Entity\\User' . "\0" . 'department', '' . "\0" . 'App\\Entity\\User' . "\0" . 'posts', '' . "\0" . 'App\\Entity\\User' . "\0" . 'comments', '' . "\0" . 'App\\Entity\\User' . "\0" . 'attendances', '' . "\0" . 'App\\Entity\\User' . "\0" . 'attendanceApprovals', '' . "\0" . 'App\\Entity\\User' . "\0" . 'attendanceDisapprovals', '' . "\0" . 'App\\Entity\\User' . "\0" . 'workPosts', '' . "\0" . 'App\\Entity\\User' . "\0" . 'responses', '' . "\0" . 'App\\Entity\\User' . "\0" . 'pollings', '' . "\0" . 'App\\Entity\\User' . "\0" . 'blames', '' . "\0" . 'App\\Entity\\User' . "\0" . 'histories', '' . "\0" . 'App\\Entity\\User' . "\0" . 'linkedin', '' . "\0" . 'App\\Entity\\User' . "\0" . 'articles', '' . "\0" . 'App\\Entity\\User' . "\0" . 'tokenFcm', '' . "\0" . 'App\\Entity\\User' . "\0" . 'tasks', '' . "\0" . 'App\\Entity\\User' . "\0" . 'biblioIRIS'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'id', '' . "\0" . 'App\\Entity\\User' . "\0" . 'email', '' . "\0" . 'App\\Entity\\User' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\User' . "\0" . 'password', '' . "\0" . 'App\\Entity\\User' . "\0" . 'fName', '' . "\0" . 'App\\Entity\\User' . "\0" . 'lName', '' . "\0" . 'App\\Entity\\User' . "\0" . 'phone', '' . "\0" . 'App\\Entity\\User' . "\0" . 'birthday', '' . "\0" . 'App\\Entity\\User' . "\0" . 'adress', '' . "\0" . 'App\\Entity\\User' . "\0" . 'img', '' . "\0" . 'App\\Entity\\User' . "\0" . 'university', '' . "\0" . 'App\\Entity\\User' . "\0" . 'studyField', '' . "\0" . 'App\\Entity\\User' . "\0" . 'requests', '' . "\0" . 'App\\Entity\\User' . "\0" . 'orders', '' . "\0" . 'App\\Entity\\User' . "\0" . 'department', '' . "\0" . 'App\\Entity\\User' . "\0" . 'posts', '' . "\0" . 'App\\Entity\\User' . "\0" . 'comments', '' . "\0" . 'App\\Entity\\User' . "\0" . 'attendances', '' . "\0" . 'App\\Entity\\User' . "\0" . 'attendanceApprovals', '' . "\0" . 'App\\Entity\\User' . "\0" . 'attendanceDisapprovals', '' . "\0" . 'App\\Entity\\User' . "\0" . 'workPosts', '' . "\0" . 'App\\Entity\\User' . "\0" . 'responses', '' . "\0" . 'App\\Entity\\User' . "\0" . 'pollings', '' . "\0" . 'App\\Entity\\User' . "\0" . 'blames', '' . "\0" . 'App\\Entity\\User' . "\0" . 'histories', '' . "\0" . 'App\\Entity\\User' . "\0" . 'linkedin', '' . "\0" . 'App\\Entity\\User' . "\0" . 'articles', '' . "\0" . 'App\\Entity\\User' . "\0" . 'tokenFcm', '' . "\0" . 'App\\Entity\\User' . "\0" . 'tasks', '' . "\0" . 'App\\Entity\\User' . "\0" . 'biblioIRIS'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserIdentifier(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserIdentifier', []);

        return parent::getUserIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getFName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFName', []);

        return parent::getFName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFName(string $fName): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFName', [$fName]);

        return parent::setFName($fName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLName', []);

        return parent::getLName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLName(string $lName): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLName', [$lName]);

        return parent::setLName($lName);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone(string $phone): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthday(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthday', []);

        return parent::getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthday(\DateTimeInterface $birthday): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthday', [$birthday]);

        return parent::setBirthday($birthday);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdress', []);

        return parent::getAdress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdress(string $adress): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdress', [$adress]);

        return parent::setAdress($adress);
    }

    /**
     * {@inheritDoc}
     */
    public function getImg(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImg', []);

        return parent::getImg();
    }

    /**
     * {@inheritDoc}
     */
    public function setImg(?string $img): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImg', [$img]);

        return parent::setImg($img);
    }

    /**
     * {@inheritDoc}
     */
    public function getUniversity(): ?\App\Entity\University
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniversity', []);

        return parent::getUniversity();
    }

    /**
     * {@inheritDoc}
     */
    public function setUniversity(?\App\Entity\University $university): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUniversity', [$university]);

        return parent::setUniversity($university);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudyField(): ?\App\Entity\StudyField
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudyField', []);

        return parent::getStudyField();
    }

    /**
     * {@inheritDoc}
     */
    public function setStudyField(?\App\Entity\StudyField $studyField): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStudyField', [$studyField]);

        return parent::setStudyField($studyField);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequests(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequests', []);

        return parent::getRequests();
    }

    /**
     * {@inheritDoc}
     */
    public function addRequest(\App\Entity\Request $request): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRequest', [$request]);

        return parent::addRequest($request);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRequest(\App\Entity\Request $request): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRequest', [$request]);

        return parent::removeRequest($request);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrders(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrders', []);

        return parent::getOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrder(\App\Entity\Order $order): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrder', [$order]);

        return parent::addOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrder(\App\Entity\Order $order): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrder', [$order]);

        return parent::removeOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartment(): ?\App\Entity\Department
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartment', []);

        return parent::getDepartment();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartment(?\App\Entity\Department $department): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartment', [$department]);

        return parent::setDepartment($department);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosts', []);

        return parent::getPosts();
    }

    /**
     * {@inheritDoc}
     */
    public function addPost(\App\Entity\Post $post): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPost', [$post]);

        return parent::addPost($post);
    }

    /**
     * {@inheritDoc}
     */
    public function removePost(\App\Entity\Post $post): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePost', [$post]);

        return parent::removePost($post);
    }

    /**
     * {@inheritDoc}
     */
    public function getComments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComments', []);

        return parent::getComments();
    }

    /**
     * {@inheritDoc}
     */
    public function addComment(\App\Entity\Comment $comment): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComment', [$comment]);

        return parent::addComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeComment(\App\Entity\Comment $comment): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeComment', [$comment]);

        return parent::removeComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttendances(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttendances', []);

        return parent::getAttendances();
    }

    /**
     * {@inheritDoc}
     */
    public function addAttendance(\App\Entity\Attendance $attendance): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttendance', [$attendance]);

        return parent::addAttendance($attendance);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAttendance(\App\Entity\Attendance $attendance): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAttendance', [$attendance]);

        return parent::removeAttendance($attendance);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttendanceApprovals(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttendanceApprovals', []);

        return parent::getAttendanceApprovals();
    }

    /**
     * {@inheritDoc}
     */
    public function addAttendanceApproval(\App\Entity\AttendanceApproval $attendanceApproval): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttendanceApproval', [$attendanceApproval]);

        return parent::addAttendanceApproval($attendanceApproval);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAttendanceApproval(\App\Entity\AttendanceApproval $attendanceApproval): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAttendanceApproval', [$attendanceApproval]);

        return parent::removeAttendanceApproval($attendanceApproval);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttendanceDisapprovals(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttendanceDisapprovals', []);

        return parent::getAttendanceDisapprovals();
    }

    /**
     * {@inheritDoc}
     */
    public function addAttendanceDisapproval(\App\Entity\AttendanceDisapproval $attendanceDisapproval): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttendanceDisapproval', [$attendanceDisapproval]);

        return parent::addAttendanceDisapproval($attendanceDisapproval);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAttendanceDisapproval(\App\Entity\AttendanceDisapproval $attendanceDisapproval): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAttendanceDisapproval', [$attendanceDisapproval]);

        return parent::removeAttendanceDisapproval($attendanceDisapproval);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkPosts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkPosts', []);

        return parent::getWorkPosts();
    }

    /**
     * {@inheritDoc}
     */
    public function addWorkPost(\App\Entity\WorkPost $workPost): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addWorkPost', [$workPost]);

        return parent::addWorkPost($workPost);
    }

    /**
     * {@inheritDoc}
     */
    public function removeWorkPost(\App\Entity\WorkPost $workPost): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeWorkPost', [$workPost]);

        return parent::removeWorkPost($workPost);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponses(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponses', []);

        return parent::getResponses();
    }

    /**
     * {@inheritDoc}
     */
    public function addResponse(\App\Entity\Response $response): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addResponse', [$response]);

        return parent::addResponse($response);
    }

    /**
     * {@inheritDoc}
     */
    public function removeResponse(\App\Entity\Response $response): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeResponse', [$response]);

        return parent::removeResponse($response);
    }

    /**
     * {@inheritDoc}
     */
    public function getPollings(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPollings', []);

        return parent::getPollings();
    }

    /**
     * {@inheritDoc}
     */
    public function addPolling(\App\Entity\Polling $polling): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPolling', [$polling]);

        return parent::addPolling($polling);
    }

    /**
     * {@inheritDoc}
     */
    public function removePolling(\App\Entity\Polling $polling): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePolling', [$polling]);

        return parent::removePolling($polling);
    }

    /**
     * {@inheritDoc}
     */
    public function getBlames(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlames', []);

        return parent::getBlames();
    }

    /**
     * {@inheritDoc}
     */
    public function addBlame(\App\Entity\Blame $blame): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBlame', [$blame]);

        return parent::addBlame($blame);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBlame(\App\Entity\Blame $blame): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBlame', [$blame]);

        return parent::removeBlame($blame);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistories(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistories', []);

        return parent::getHistories();
    }

    /**
     * {@inheritDoc}
     */
    public function addHistory(\App\Entity\History $history): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHistory', [$history]);

        return parent::addHistory($history);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHistory(\App\Entity\History $history): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHistory', [$history]);

        return parent::removeHistory($history);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkedin(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkedin', []);

        return parent::getLinkedin();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinkedin(?string $linkedin): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkedin', [$linkedin]);

        return parent::setLinkedin($linkedin);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticles(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticles', []);

        return parent::getArticles();
    }

    /**
     * {@inheritDoc}
     */
    public function addArticle(\App\Entity\Article $article): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArticle', [$article]);

        return parent::addArticle($article);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArticle(\App\Entity\Article $article): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArticle', [$article]);

        return parent::removeArticle($article);
    }

    /**
     * {@inheritDoc}
     */
    public function getTokenFcm(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTokenFcm', []);

        return parent::getTokenFcm();
    }

    /**
     * {@inheritDoc}
     */
    public function setTokenFcm(?string $tokenFcm): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTokenFcm', [$tokenFcm]);

        return parent::setTokenFcm($tokenFcm);
    }

    /**
     * {@inheritDoc}
     */
    public function getTasks(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTasks', []);

        return parent::getTasks();
    }

    /**
     * {@inheritDoc}
     */
    public function addTask(\App\Entity\Task $task): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTask', [$task]);

        return parent::addTask($task);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTask(\App\Entity\Task $task): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTask', [$task]);

        return parent::removeTask($task);
    }

    /**
     * {@inheritDoc}
     */
    public function getBiblioIRIS(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiblioIRIS', []);

        return parent::getBiblioIRIS();
    }

    /**
     * {@inheritDoc}
     */
    public function addBiblioIRI(\App\Entity\BiblioIRIS $biblioIRI): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBiblioIRI', [$biblioIRI]);

        return parent::addBiblioIRI($biblioIRI);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBiblioIRI(\App\Entity\BiblioIRIS $biblioIRI): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBiblioIRI', [$biblioIRI]);

        return parent::removeBiblioIRI($biblioIRI);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
