<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Post extends \App\Entity\Post implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'publishDate', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'targets', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'author', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'comments', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'engagementPost', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'announcement', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'departments', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'poll'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'publishDate', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'targets', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'author', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'comments', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'engagementPost', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'announcement', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'departments', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'poll'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Post $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishDate', []);

        return parent::getPublishDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishDate(\DateTimeInterface $publishDate): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishDate', [$publishDate]);

        return parent::setPublishDate($publishDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getTargets(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTargets', []);

        return parent::getTargets();
    }

    /**
     * {@inheritDoc}
     */
    public function setTargets(?string $targets): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTargets', [$targets]);

        return parent::setTargets($targets);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthor(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthor', []);

        return parent::getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthor(?\App\Entity\User $author): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthor', [$author]);

        return parent::setAuthor($author);
    }

    /**
     * {@inheritDoc}
     */
    public function getComments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComments', []);

        return parent::getComments();
    }

    /**
     * {@inheritDoc}
     */
    public function addComment(\App\Entity\Comment $comment): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComment', [$comment]);

        return parent::addComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeComment(\App\Entity\Comment $comment): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeComment', [$comment]);

        return parent::removeComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getEngagementPost(): ?\App\Entity\EngagementPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEngagementPost', []);

        return parent::getEngagementPost();
    }

    /**
     * {@inheritDoc}
     */
    public function setEngagementPost(\App\Entity\EngagementPost $engagementPost): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEngagementPost', [$engagementPost]);

        return parent::setEngagementPost($engagementPost);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnouncement(): ?\App\Entity\Announcement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnouncement', []);

        return parent::getAnnouncement();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnouncement(\App\Entity\Announcement $announcement): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnouncement', [$announcement]);

        return parent::setAnnouncement($announcement);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartments', []);

        return parent::getDepartments();
    }

    /**
     * {@inheritDoc}
     */
    public function addDepartment(\App\Entity\Department $department): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDepartment', [$department]);

        return parent::addDepartment($department);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDepartment(\App\Entity\Department $department): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDepartment', [$department]);

        return parent::removeDepartment($department);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoll(): ?\App\Entity\Poll
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoll', []);

        return parent::getPoll();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoll(\App\Entity\Poll $poll): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoll', [$poll]);

        return parent::setPoll($poll);
    }

}
