<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Form extends \App\Entity\Form implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Form' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Form' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Form' . "\0" . 'creaDate', '' . "\0" . 'App\\Entity\\Form' . "\0" . 'training', '' . "\0" . 'App\\Entity\\Form' . "\0" . 'workshop', '' . "\0" . 'App\\Entity\\Form' . "\0" . 'fields'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Form' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Form' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Form' . "\0" . 'creaDate', '' . "\0" . 'App\\Entity\\Form' . "\0" . 'training', '' . "\0" . 'App\\Entity\\Form' . "\0" . 'workshop', '' . "\0" . 'App\\Entity\\Form' . "\0" . 'fields'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Form $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Form
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreaDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreaDate', []);

        return parent::getCreaDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreaDate(\DateTimeInterface $creaDate): \App\Entity\Form
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreaDate', [$creaDate]);

        return parent::setCreaDate($creaDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getTraining(): ?\App\Entity\Training
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTraining', []);

        return parent::getTraining();
    }

    /**
     * {@inheritDoc}
     */
    public function setTraining(\App\Entity\Training $training): \App\Entity\Form
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTraining', [$training]);

        return parent::setTraining($training);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkshop(): ?\App\Entity\Workshop
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkshop', []);

        return parent::getWorkshop();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkshop(\App\Entity\Workshop $workshop): \App\Entity\Form
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkshop', [$workshop]);

        return parent::setWorkshop($workshop);
    }

    /**
     * {@inheritDoc}
     */
    public function getFields(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFields', []);

        return parent::getFields();
    }

    /**
     * {@inheritDoc}
     */
    public function addField(\App\Entity\Field $field): \App\Entity\Form
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addField', [$field]);

        return parent::addField($field);
    }

    /**
     * {@inheritDoc}
     */
    public function removeField(\App\Entity\Field $field): \App\Entity\Form
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeField', [$field]);

        return parent::removeField($field);
    }

}
