<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WorkPost extends \App\Entity\WorkPost implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\WorkPost' . "\0" . 'id', '' . "\0" . 'App\\Entity\\WorkPost' . "\0" . 'engagementPost', '' . "\0" . 'App\\Entity\\WorkPost' . "\0" . 'sg', '' . "\0" . 'App\\Entity\\WorkPost' . "\0" . 'agendas', '' . "\0" . 'App\\Entity\\WorkPost' . "\0" . 'meeting', '' . "\0" . 'App\\Entity\\WorkPost' . "\0" . 'workshop'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\WorkPost' . "\0" . 'id', '' . "\0" . 'App\\Entity\\WorkPost' . "\0" . 'engagementPost', '' . "\0" . 'App\\Entity\\WorkPost' . "\0" . 'sg', '' . "\0" . 'App\\Entity\\WorkPost' . "\0" . 'agendas', '' . "\0" . 'App\\Entity\\WorkPost' . "\0" . 'meeting', '' . "\0" . 'App\\Entity\\WorkPost' . "\0" . 'workshop'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WorkPost $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEngagementPost(): ?\App\Entity\EngagementPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEngagementPost', []);

        return parent::getEngagementPost();
    }

    /**
     * {@inheritDoc}
     */
    public function setEngagementPost(\App\Entity\EngagementPost $engagementPost): \App\Entity\WorkPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEngagementPost', [$engagementPost]);

        return parent::setEngagementPost($engagementPost);
    }

    /**
     * {@inheritDoc}
     */
    public function getSg(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSg', []);

        return parent::getSg();
    }

    /**
     * {@inheritDoc}
     */
    public function setSg(?\App\Entity\User $sg): \App\Entity\WorkPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSg', [$sg]);

        return parent::setSg($sg);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgendas(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgendas', []);

        return parent::getAgendas();
    }

    /**
     * {@inheritDoc}
     */
    public function addAgenda(\App\Entity\Agenda $agenda): \App\Entity\WorkPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAgenda', [$agenda]);

        return parent::addAgenda($agenda);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAgenda(\App\Entity\Agenda $agenda): \App\Entity\WorkPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAgenda', [$agenda]);

        return parent::removeAgenda($agenda);
    }

    /**
     * {@inheritDoc}
     */
    public function getMeeting(): ?\App\Entity\Meeting
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeeting', []);

        return parent::getMeeting();
    }

    /**
     * {@inheritDoc}
     */
    public function setMeeting(\App\Entity\Meeting $meeting): \App\Entity\WorkPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMeeting', [$meeting]);

        return parent::setMeeting($meeting);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkshop(): ?\App\Entity\Workshop
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkshop', []);

        return parent::getWorkshop();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkshop(\App\Entity\Workshop $workshop): \App\Entity\WorkPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkshop', [$workshop]);

        return parent::setWorkshop($workshop);
    }

}
