<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EngagementPost extends \App\Entity\EngagementPost implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'id', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'place', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'date', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'link', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'start', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'end', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'canceled', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'post', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'attendances', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'attendanceApprovals', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'attendanceDisapprovals', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'workPost', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'training'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'id', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'place', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'date', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'link', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'start', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'end', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'canceled', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'post', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'attendances', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'attendanceApprovals', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'attendanceDisapprovals', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'workPost', '' . "\0" . 'App\\Entity\\EngagementPost' . "\0" . 'training'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EngagementPost $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlace(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlace', []);

        return parent::getPlace();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlace(?string $place): \App\Entity\EngagementPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlace', [$place]);

        return parent::setPlace($place);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate(\DateTimeInterface $date): \App\Entity\EngagementPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getLink(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLink', []);

        return parent::getLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setLink(?string $link): \App\Entity\EngagementPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLink', [$link]);

        return parent::setLink($link);
    }

    /**
     * {@inheritDoc}
     */
    public function getStart(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStart', []);

        return parent::getStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setStart(\DateTimeInterface $start): \App\Entity\EngagementPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStart', [$start]);

        return parent::setStart($start);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnd(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnd', []);

        return parent::getEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnd(\DateTimeInterface $end): \App\Entity\EngagementPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnd', [$end]);

        return parent::setEnd($end);
    }

    /**
     * {@inheritDoc}
     */
    public function getCanceled(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCanceled', []);

        return parent::getCanceled();
    }

    /**
     * {@inheritDoc}
     */
    public function setCanceled(?bool $canceled): \App\Entity\EngagementPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCanceled', [$canceled]);

        return parent::setCanceled($canceled);
    }

    /**
     * {@inheritDoc}
     */
    public function getPost(): ?\App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPost', []);

        return parent::getPost();
    }

    /**
     * {@inheritDoc}
     */
    public function setPost(\App\Entity\Post $post): \App\Entity\EngagementPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPost', [$post]);

        return parent::setPost($post);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttendances(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttendances', []);

        return parent::getAttendances();
    }

    /**
     * {@inheritDoc}
     */
    public function addAttendance(\App\Entity\Attendance $attendance): \App\Entity\EngagementPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttendance', [$attendance]);

        return parent::addAttendance($attendance);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAttendance(\App\Entity\Attendance $attendance): \App\Entity\EngagementPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAttendance', [$attendance]);

        return parent::removeAttendance($attendance);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttendanceApprovals(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttendanceApprovals', []);

        return parent::getAttendanceApprovals();
    }

    /**
     * {@inheritDoc}
     */
    public function addAttendanceApproval(\App\Entity\AttendanceApproval $attendanceApproval): \App\Entity\EngagementPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttendanceApproval', [$attendanceApproval]);

        return parent::addAttendanceApproval($attendanceApproval);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAttendanceApproval(\App\Entity\AttendanceApproval $attendanceApproval): \App\Entity\EngagementPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAttendanceApproval', [$attendanceApproval]);

        return parent::removeAttendanceApproval($attendanceApproval);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttendanceDisapprovals(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttendanceDisapprovals', []);

        return parent::getAttendanceDisapprovals();
    }

    /**
     * {@inheritDoc}
     */
    public function addAttendanceDisapproval(\App\Entity\AttendanceDisapproval $attendanceDisapproval): \App\Entity\EngagementPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttendanceDisapproval', [$attendanceDisapproval]);

        return parent::addAttendanceDisapproval($attendanceDisapproval);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAttendanceDisapproval(\App\Entity\AttendanceDisapproval $attendanceDisapproval): \App\Entity\EngagementPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAttendanceDisapproval', [$attendanceDisapproval]);

        return parent::removeAttendanceDisapproval($attendanceDisapproval);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkPost(): ?\App\Entity\WorkPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkPost', []);

        return parent::getWorkPost();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkPost(\App\Entity\WorkPost $workPost): \App\Entity\EngagementPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkPost', [$workPost]);

        return parent::setWorkPost($workPost);
    }

    /**
     * {@inheritDoc}
     */
    public function getTraining(): ?\App\Entity\Training
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTraining', []);

        return parent::getTraining();
    }

    /**
     * {@inheritDoc}
     */
    public function setTraining(\App\Entity\Training $training): \App\Entity\EngagementPost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTraining', [$training]);

        return parent::setTraining($training);
    }

}
